name: habitto
description: "Una aplicación inmobiliaria moderna"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  video_player: ^2.8.1
  http: ^1.1.0
  dio: ^5.4.0
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  mapbox_maps_flutter: 2.11.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  camera: ^0.10.5+7
  auto_size_text: ^3.0.0
  web_socket_channel: ^2.4.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  sign_in_with_apple: ^6.0.0
  speech_to_text: ^6.3.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  image: ^4.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700

# Configuración del icono de la aplicación
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoHabitto.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logoHabitto.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logoHabitto.png"
  android_12:
    image: "assets/images/logoHabitto.png"
    icon_background_color: "#FFFFFF"
