name: habitto
description: "Una aplicaciÃ³n inmobiliaria moderna"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  video_player: ^2.8.1
  http: ^1.1.0
  dio: ^5.4.0
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  mapbox_maps_flutter: ^2.0.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
